scripts/c511005028.lua
scripts/c511005032.lua
scripts/c511005040.lua
scripts/c511005045.lua
scripts/c511005048.lua
scripts/c511005055.lua
scripts/c511005056.lua
scripts/c511005063.lua
scripts/c511005066.lua
scripts/c511005070.lua
scripts/c511005078.lua
scripts/c511005088.lua

- None
====
- 511005032 Line World
- fix: proper send to grave
- update phase detection to current ygopro's method
- 511005028 Overlay Banish
- 511005055 Flattery
- 511005056 Reservation Reward
- 511005070 Shield Fin
- 511005088 Performapal Reborn Force
- Defence -> Defense
- 511005040 Surprise Inspection
- 511005045 Galactic Fury
- 511005048 Smoke Mirror
- 511005063 Magical Hats (Anime)
- 511005066 Knight Hunger Monger
- 511005078 Guard Plus

Shad3's commits 8/20

---

scripts/c511009193.lua

fixed a bug where the option to attack appear but you could do nothing

Lyrical Luscinia - Assemble Nightingale Fix

---

scripts/c511000167.lua

Dark wall of wind

---

scripts/c511007007.lua

Script Cleanup and BP issue fixed

Battle of Sleeping Spirits

---

scripts/c95000177.lua

fixed effect and activate in hand during either's turn

Action Card Encore Fix

---

scripts/c511009017.lua

gearspring spirit Fix

---

scripts/c511009059.lua

white mirror fixe

---

scripts/c511005010.lua
scripts/c511005014.lua
scripts/c511005017.lua
scripts/c511005021.lua
scripts/c511005063.lua
scripts/c511005067.lua

- restructure Magical Hats (Anime)
- typo fixes (I swear I've fixed most of these before... maybe I forgot or something)

Typo fix + Magical Hats (Anime)

---

scripts/c511009053.lua

D hero Dystopiaguy fix

---

scripts/c511009026.lua

Removed the "Predator Plant" Collection and added the "Predator Plant" Setcode

Predator Planter Update

---

scripts/c511005092.lua

more "race" function overrides:
- Card.GetOriginalRace
- Card.GetPreviousRaceOnField
- ~~Duel.IsPlayerCanSpecialSummonMonster~~ not needed

Sealed Duel - more overrides

---

scripts/c511009328.lua

fixed the setcode used for phantom knight
removed some old part that were used for testing purpose

Phantom Knight Setcode Fixe

---

scripts/c511001429.lua
scripts/c511001431.lua
scripts/c511002871.lua
scripts/c511002872.lua

Added The Effect that checks The Rank Up of the Numbers.
PS: the CDB Has Changed As well So Please Update it.

Fixed the Number C Rank Up

---

scripts/c511004321.lua
scripts/c511004324.lua
scripts/c511005610.lua

fixes- 3 DOR cards

---

scripts/c511009345.lua

Corrected a bug where you could activate the card without having 2 Parasite fusioner in the grave

parasitic Double Rebirth fix

---

scripts/c511009365.lua

D/D Ghost Fix

---

scripts/c511009107.lua

fixed a 2 "activate in pzone" effect
fixed a bug that allowed protected for any monster on the field

fixed Pm bubble gardna

---

scripts/c511009367.lua

removed the flag to check if it activated its effect
added description for the last effect

Spirit Crystal - Salamander fix

---

scripts/c511009366.lua

flag to check if it activated a effect now in STF effect

Perfected STF effect

---

scripts/c511009327.lua

RUM Burial of The Phantom Knights Fix

---

scripts/c511009054.lua

RUM The Phantom Knights of Launch fix

---

scripts/c511001371.lua
scripts/c511001372.lua
scripts/c511001429.lua
scripts/c511001430.lua
scripts/c511001431.lua
scripts/c511001659.lua
scripts/c511001777.lua
scripts/c511001781.lua
scripts/c511002482.lua
scripts/c511002855.lua
scripts/c511002866.lua
scripts/c511002871.lua
scripts/c511002872.lua
scripts/c511010165.lua
scripts/c511010192.lua
scripts/c511010238.lua
scripts/c511010239.lua
scripts/c513000059.lua
scripts/c513000063.lua

Fixed the Rank Up check with OCG ruling. 
Fixed the Chaos Numbers and CXyz Rank up gained effect.

Fixed the Rank Up check with OCG ruling.

---

scripts/c511009170.lua

Fixed Bamboo horse

---

scripts/c511009381.lua

https://github.com/EerieCode/Live2016/commit/540a2962edf6315c838ae9077a3fdfc2cc79d825
@ClementLouis

Fixed Greedy Venom Self target

---

scripts/c513000083.lua

https://github.com/Ygoproco/Live2016/pull/252

Fix of DZW - Chimera Clad (Anime) By Eclair11

---

scripts/c511004127.lua

fix for card

---

scripts/c511009315.lua

fix on anime cards

---

scripts/c513000013.lua

Red Nova Dragon (Anime) missing script

---

scripts/c511009025.lua

Fixed the damage inflicted (counted the atk of indestructable monsters before)

Starve Venom Fusion Dragon Fix

---

scripts/c511009321.lua

Fixed The Phantom Knights of Cursed Javelin

---

scripts/c511009437.lua
scripts/c511009441.lua
scripts/c511009442.lua
scripts/c511009443.lua

http://yugioh.wikia.com/wiki/Supreme_King
Also Fixed Supreme King Servant Dragon Darkvrm (Anime)

Fixed OCG Supreme King collection Missing Members

---

scripts/c511001646.lua

we still need a way for level 0

Fixed for negative levels

---

scripts/c511009343.lua

Updated The Phantom Knights of Possession for the new core

Updated The Phantom Knights of Possession
